extends RefCounted

const GROUPS := {
	"PLAYER": ["max_health", "starting_health"],
	"MOVEMENT": ["move_speed", "sprint_speed", "crouch_speed", "jump_height", "jump_speed", "max_jumps", "block_speed_multiplier"],
	"COMBAT": ["attack_speed", "attack_damage", "damage_multiplier", "attack_range", "air_damage_multiplier", "knockback_strength", "respawn_seconds"],
	"STAMINA": ["max_stamina", "stamina_drain", "stamina_regen", "stamina_regen_delay"],
	"MATCH": ["round_duration", "knockouts_to_win", "total_rounds", "ready_check_seconds", "arena_start_countdown"],
	"WORLD": ["gravity", "max_fall_speed", "fall_damage", "fall_damage_threshold", "fall_damage_multiplier"],
	"CAMERA": ["camera_fov", "camera_distance", "camera_height", "camera_vertical_offset", "camera_min_pitch", "camera_max_pitch", "camera_rotation_speed", "camera_smoothing", "camera_follow_speed", "camera_zoom_min", "camera_zoom_max"],
	"SWORD OBJECTIVE": ["sword_objective_enabled", "crystal_max_health", "crystal_damage_per_punch", "crystal_break_stages", "sword_accessibility_threshold", "sword_pickup_range", "sword_pickup_hold_time"],
	"SWORD COMBAT": ["sword_damage", "sword_range", "sword_swing_arc", "sword_swing_speed", "sword_attack_recovery", "sword_knockback", "sword_blockable", "sword_block_damage_reduction", "sword_movement_speed_multiplier"],
	"SWORD CRITICAL": ["sword_jump_critical_enabled", "sword_critical_damage_multiplier"],
}
# Key, label, minimum, maximum, step, default, unit. The server clamps shared rules.
const FIELDS := [
	["sword_objective_enabled", "Sword objective enabled", 0, 1, 1, 1, ""],
	["crystal_max_health", "Crystal maximum health", 10, 1000, 10, 100, " HP"],
	["crystal_damage_per_punch", "Crystal damage per punch", 1, 100, 1, 10, " HP"],
	["crystal_break_stages", "Crystal break stages", 2, 8, 1, 4, ""],
	["sword_accessibility_threshold", "Sword accessibility threshold", 0, 1, 0.05, 0.25, ""],
	["sword_pickup_range", "Sword pickup range", 0.5, 5, 0.1, 2.2, " m"],
	["sword_pickup_hold_time", "Sword pickup hold time", 0, 5, 0.1, 0, " s"],
	["sword_damage", "Sword damage", 1, 200, 1, 30, " HP"],
	["sword_range", "Sword range", 1, 8, 0.1, 3.4, " m"],
	["sword_swing_arc", "Sword swing arc", 0.2, 3.14, 0.1, 1.2, " rad"],
	["sword_swing_speed", "Sword swing speed", 0.2, 5, 0.1, 1, " ×"],
	["sword_attack_recovery", "Sword attack recovery", 0.2, 5, 0.1, 1.2, " s"],
	["sword_knockback", "Sword knockback", 0, 20, 0.5, 4, ""],
	["sword_blockable", "Sword blockable", 0, 1, 1, 1, ""],
	["sword_block_damage_reduction", "Sword block damage reduction", 0, 1, 0.05, 0.8, ""],
	["sword_movement_speed_multiplier", "Sword movement speed", 0.2, 2, 0.05, 1, " ×"],
	["sword_jump_critical_enabled", "Sword jump critical", 0, 1, 1, 1, ""],
	["sword_critical_damage_multiplier", "Sword critical multiplier", 1, 5, 0.1, 2, " ×"],
	["max_health", "Maximum health", 10, 1000, 10, 100, " HP"],
	["starting_health", "Starting / respawn health", 1, 1000, 1, 100, " HP"],
	["move_speed", "Normal move speed", 1, 20, 0.1, 5.5, " m/s"],
	["sprint_speed", "Sprint speed", 1, 30, 0.1, 9, " m/s"],
	["crouch_speed", "Crouch speed", 0.1, 15, 0.1, 2.5, " m/s"],
	["jump_height", "Jump strength / height", 0.25, 10, 0.025, 1.225, " m"],
	["jump_speed", "Jump speed / airtime", 0.25, 3, 0.05, 1, " ×"],
	["max_jumps", "Jumps before landing", 1, 10, 1, 1, ""],
	["block_speed_multiplier", "Move speed while blocking", 0, 1, 0.01, 2.5 / 5.5, " ×"],
	["attack_speed", "Attack speed", 0.2, 10, 0.1, 2, " /s"],
	["attack_damage", "Base attack damage", 0, 100, 1, 10, " HP"],
	["damage_multiplier", "Player damage multiplier", 0, 10, 0.1, 1, " ×"],
	["attack_range", "Punch range", 0.5, 5, 0.1, 2.2, " m"],
	["air_damage_multiplier", "Airborne critical damage", 1, 5, 0.1, 2, " ×"],
	["knockback_strength", "Knockback strength", 0, 15, 0.1, 2, " m/s"],
	["respawn_seconds", "Respawn time", 0.5, 10, 0.5, 3, " s"],
	["max_stamina", "Maximum stamina", 1, 1000, 1, 100, ""],
	["stamina_drain", "Sprint stamina drain", 0, 200, 1, 25, " /s"],
	["stamina_regen", "Stamina regeneration", 0, 200, 1, 20, " /s"],
	["stamina_regen_delay", "Regeneration delay", 0, 10, 0.1, 1, " s"],
	["round_duration", "Round duration", 10, 1800, 1, 150, " s"],
	["knockouts_to_win", "Knockouts to win round", 1, 50, 1, 4, ""],
	["total_rounds", "Number of rounds", 1, 50, 1, 10, ""],
	["ready_check_seconds", "Ready-check timer", 3, 120, 1, 15, " s"],
	["arena_start_countdown", "Arena start countdown", 0, 60, 1, 10, " s"],
	["gravity", "Gravity", 1, 80, 0.5, 20, " m/s²"],
	["max_fall_speed", "Maximum falling speed", 1, 100, 1, 30, " m/s"],
	["fall_damage", "Fall damage", 0, 1, 1, 0, ""],
	["fall_damage_threshold", "Safe fall distance", 0, 50, 0.25, 4, " m"],
	["fall_damage_multiplier", "Damage per extra fall metre", 0, 100, 1, 10, " HP/m"],
	["camera_fov", "Camera field of view", 35, 90, 1, 55, "°"], ["camera_distance", "Camera distance", 8, 20, 0.1, 11.5, " m"], ["camera_height", "Camera height", 5, 30, 0.1, 11, " m"], ["camera_vertical_offset", "Camera vertical offset", -3, 8, 0.1, 1, " m"],
	["camera_min_pitch", "Camera minimum pitch", 20, 85, 1, 35, "°"], ["camera_max_pitch", "Camera maximum pitch", 20, 89, 1, 75, "°"], ["camera_rotation_speed", "Camera rotation speed", 0.1, 5, 0.05, 1, " ×"], ["camera_smoothing", "Camera smoothing", 0, 1, 0.05, 0.85, " ×"], ["camera_follow_speed", "Camera follow speed", 1, 30, 0.5, 16, " ×"], ["camera_zoom_min", "Camera zoom minimum", 4, 20, 0.1, 8, " m"], ["camera_zoom_max", "Camera zoom maximum", 10, 40, 0.1, 20, " m"],
]
