import test from 'node:test';
import assert from 'node:assert/strict';
import { fixture, connect, create, join, expectError, input, action, player, moveTo, requestBattle, startBattle, pause } from './helpers.mjs';

test('Town is shared, movable and unconditionally safe despite damaging host rules', async t => {
  const server = await fixture(t);
  const [host, guest] = await Promise.all([connect(server), connect(server)]);
  const room = await create(host);
  const joined = await join(guest, room.code);
  assert.equal(joined.zone, 'town');
  assert.equal(joined.safe_zone, true);
  assert.equal(joined.match.phase, 'town');
  const initial = await guest.wait(message => message.type === 'state' && message.players.length === 2);
  assert.deepEqual(initial.players.map(p => [p.x, p.z]), [[-3, 2], [3, 2]]);
  host.send({ type: 'god_options', options: { god_mode: false, attack_damage: 100,
    fall_damage: true, fall_damage_threshold: 0, fall_damage_multiplier: 100, knockback_strength: 15 } });
  await guest.wait(message => message.type === 'room' && message.god_options.fall_damage === true);
  await Promise.all([moveTo(host, 0, -3), moveTo(guest, 0, -4.5)]);
  input(host);
  input(guest);
  // Capture the actual settled position, rather than the approximate moveTo goal.
  await pause(300);
  const beforePunch = { ...player(host, guest.id) };
  const from = host.mark();
  action(host, 'punch');
  await host.wait(message => message.type === 'combat' && message.kind === 'blocked' && message.target === guest.id, { from });
  assert.equal(player(host, guest.id).health, 100);
  const hitTick = host.latest.tick;
  await host.wait(message => message.type === 'state' && message.tick > hitTick, { from: host.mark() });
  assert.equal(player(host, guest.id).z, beforePunch.z, 'Safe punches cause no Z knockback.');
  assert.equal(player(host, guest.id).x, beforePunch.x, 'Safe punches cause no X knockback.');
  const jumpFrom = guest.mark();
  action(guest, 'jump');
  const airborne = await guest.wait(message => message.type === 'state' && message.players.some(p => p.id === guest.id && !p.grounded), { from: jumpFrom });
  await guest.wait(message => message.type === 'state' && message.tick > airborne.tick && message.players.some(p => p.id === guest.id && p.grounded), { from: jumpFrom });
  assert.equal(player(guest).health, 100, 'Town overrides enabled lethal fall damage.');
  assert.equal(guest.messages.slice(jumpFrom).some(message => message.kind === 'defeat'), false);
  assert.equal(guest.room.god_options.god_mode, false, 'The battle God option remains unchanged.');
  await expectError(guest, { type: 'god_options', options: { god_mode: false } }, /Only the room host/);
});

test('Old Man requires the nearby host; ready timeout cancels without teleport and unanimous fresh readiness enters arena', async t => {
  const server = await fixture(t);
  const [host, guest] = await Promise.all([connect(server), connect(server)]);
  const room = await create(host);
  await join(guest, room.code);
  await expectError(host, { type: 'start' }, /closer to the Old Man/);
  await expectError(guest, { type: 'start' }, /Only the room host/);
  await expectError(host, { type: 'restart' }, /Old Man/);
  await expectError(host, { type: 'ready', ready: true }, /during a ready check/);
  host.send({ type: 'god_options', options: { ready_check_seconds: 3, attack_damage: 25, knockback_strength: 0 } });
  await guest.wait(message => message.type === 'room' && message.god_options.ready_check_seconds === 3);
  const check = await requestBattle(host);
  assert.ok(check.players.every(p => p.ready === false));
  assert.equal(check.match.ready_time_left, 3);
  assert.equal(check.safe_zone, true);
  const positions = host.latest.players.map(p => [p.id, p.x, p.z]);
  const timeoutFrom = host.mark();
  host.send({ type: 'ready', ready: true });
  await expectError(guest, { type: 'cancel_start' }, /Only the room host/);
  await expectError(host, { type: 'set_mode', mode: 'teams' }, /Town Lobby/);
  const cancelled = await host.wait(message => message.type === 'room' && message.phase === 'lobby', { from: timeoutFrom, timeout: 4500 });
  assert.ok(cancelled.players.every(p => !p.ready));
  assert.equal(cancelled.match.phase, 'town');
  assert.equal(host.messages.slice(timeoutFrom).some(message => message.phase === 'playing'), false);
  assert.deepEqual(host.latest.players.map(p => [p.id, p.x, p.z]), positions, 'Timeout does not teleport anyone.');
  const playing = await startBattle(host, [host, guest]);
  assert.equal(playing.zone, 'arena');
  assert.equal(playing.safe_zone, false);
  assert.equal(playing.match.phase, 'round');
  assert.equal(playing.match.round_number, 1);
  assert.equal(playing.match.time_left, 150);
  assert.equal(playing.match.score_entries.length, 2);
  assert.deepEqual(playing.players.map(p => [p.x, p.z]), [[-4, 0], [4, 0]]);
  await expectError(host, { type: 'set_mode', mode: 'teams' }, /Town Lobby/);
  await expectError(guest, { type: 'set_party', party: 0 }, /Town Lobby/);
  await Promise.all([moveTo(host, 0, 0), moveTo(guest, 0, -1.5)]);
  input(host);
  const hitFrom = host.mark();
  action(host, 'punch');
  const hit = await host.wait(message => message.type === 'combat' && message.kind === 'hit', { from: hitFrom });
  assert.equal(hit.damage, 25, 'Normal battle damage returns after leaving Town.');
  await host.wait(message => message.type === 'state' && message.players.some(p => p.id === guest.id && p.health === 75), { from: hitFrom });
  const townFrom = host.mark();
  host.send({ type: 'lobby' });
  const returned = await host.wait(message => message.type === 'state' && message.zone === 'town', { from: townFrom });
  assert.equal(returned.safe_zone, true);
  assert.ok(returned.players.every(p => p.health === 100 && p.stamina === 100 && !p.sprinting));
  assert.deepEqual(returned.match.round_scores, {});
  assert.deepEqual(returned.players.map(p => [p.x, p.z]), [[-3, 2], [3, 2]]);
});

test('arrival cancels a ready check, host can cancel, and departure transfers authority back in safe Town', async t => {
  const server = await fixture(t);
  const [host, guest, newcomer] = await Promise.all([connect(server), connect(server), connect(server)]);
  const room = await create(host);
  await join(guest, room.code);
  await requestBattle(host);
  host.send({ type: 'ready', ready: true });
  const from = host.mark();
  await join(newcomer, room.code, 'Newcomer');
  const arrival = await host.wait(message => message.type === 'room' && message.phase === 'lobby' && message.players.length === 3, { from });
  assert.ok(arrival.players.every(p => !p.ready));
  await requestBattle(host);
  const cancelFrom = host.mark();
  host.send({ type: 'cancel_start' });
  await host.wait(message => message.type === 'room' && message.phase === 'lobby', { from: cancelFrom });
  await startBattle(host, [host, guest, newcomer]);
  const leaveFrom = guest.mark();
  host.ws.terminate();
  const transferred = await guest.wait(message => message.type === 'room' && message.host_id === guest.id, { from: leaveFrom });
  assert.equal(transferred.phase, 'lobby');
  assert.equal(transferred.safe_zone, true);
  assert.ok(transferred.players.every(p => !p.ready));
  await expectError(newcomer, { type: 'god_options', options: { god_mode: true } }, /Only the room host/);
  guest.send({ type: 'god_options', options: { god_mode: true } });
  await newcomer.wait(message => message.type === 'room' && message.god_options.god_mode === true, { from: newcomer.mark() });
});
